# Install desktop components
#

---
- hosts: all
  tasks:
    - name: Install packages
      apt:
        pkg: "{{ item }}"
        state: present
        install_recommends: no
      loop:
        - ubuntu-mate-core        # Core desktop wuth no recommended packages
        - lightdm                 # Provide a login mechanism on boot
        - lightdm-gtk-greeter     # Provide a login mechanism on boot
        - mate-applet-brisk-menu  # Install the default start menu
        - indicator-datetime      # Provide the clock
        - indicator-power         # Show power (battery, etc)
        - indicator-sound         # Offer sound settings
      become: yes
      when: is_desktop
      notify: Start Desktop

  # This is here so that we only start the service if packages were installed
  handlers:
    - name: Start Desktop
      service:
        name: lightdm
        state: started
