# Install desktop components
#

---
- hosts: all
  tasks:
    - name: Install packages
      apt:
        pkg: "{{ item }}"
        state: present
      loop:
        - ubuntu-mate-core
      become: yes
      when: is_desktop
