# All the creature comforts for me!
---
- hosts: all
  tasks:
    - name: "Set localtime to Central"
      file:
        path: /etc/localtime
        state: link
        src: "/usr/share/zoneinfo/{{ timezone }}"
    - name: "Populate timezone file"
      copy:
        dest: /etc/timezone
        content: "{{ timezone }}\n"

